language: node_js
node_js:
  - 10
script: 
  - yarn build
  - yarn docs:build
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - echo "[DRY RUN] Attempting to deploy $TRAVIS_TAG to npm"
      - echo "//registry.npmjs.org/:_authToken=${NPM_API_TOKEN}" > ~/.npmrc
      - echo "//registry.npmjs.org/:email=${NPM_EMAIL}" >> ~/.npmrc
      - cd dist/
      - npm publish --access public --dry-run
    on:
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script:
      - echo "Attempting to deploy $TRAVIS_TAG to npm"
      - echo "//registry.npmjs.org/:_authToken=${NPM_API_TOKEN}" > ~/.npmrc
      - echo "//registry.npmjs.org/:email=${NPM_EMAIL}" >> ~/.npmrc
      - cd dist/
      - npm publish --access public --tag $TRAVIS_TAG
    on:
      tags: true
  - provider: surge
    skip_cleanup: true
    project: out
    login: $SURGE_LOGIN
    token: $SURGE_TOKEN
    domain: $SURGE_DOMAIN
    on:
      tags: true
