language: node_js
node_js:
  - 10
jobs:
  include:
    - stage: build
      script: "yarn build"
    - stage: docs
      script: "yarn docs"
stages:
  - build
  - docs
deploy:
  - provider: npm
    skip_cleanup: true
    access: public
    src: ./dist
    # email:
    # api_key:
    on:
      tags: true
  - provider: surge
    skip_cleanup: true
    project: ./out
    # login:
    # token:
    # domain:
    on:
      tags: true
